### ISSUE TITLE
Bug for edge case

### ISSUE THREAD

**Issue by zLuki** [Project-QR-Code/QR-Code#19]
Reed Solomon code not working for edge case strings: "sU&-/" and "k-%-"

If you don't know how to fix, I suggest you reading the description of my [Kata on Codewars](https://www.codewars.com/kata/5fa50a5def5ecf0014debd73)!

If you have any questions go ahead and ask 😉

**Comment by kaffarell** [comment]
The generator uses the small version of the QR-Code, which only supports the alphabet and numbers.
